server:
  port: 8001

eureka:
  instance:
    # 单机 hostname: localhost #eureka注册中心实例名称
    hostname: peer2 # 集群
  client:
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url:
      defaultZone: http://peer1:8000/eureka/