server:
  port: 9000
spring:
  application:
    name: springcloud-provider-service
eureka:
  client:
    register-with-eureka: true     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    registry-fetch-interval-seconds: 5 # 默认为30秒
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://xxx:xxx@localhost:8000/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
