server:
  port: 9001
spring:
  application:
    name: springcloud-consumer-service
eureka:
  client:
    register-with-eureka: true     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://lvlq:arsenal73@localhost:8000/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
feign:
  hystrix:
    enabled: true