#高可用服务化配置中心
server:
  port: 7001
spring:
  cloud:
    config:
      server:
        git:
            uri: https://github.com/lvlq73/config/
            search-paths: config-repo
            username: lvlq73
            password: arsenal73
  application:
    name: spring-cloud-config-server
eureka:
  client:
     service-url:
      defaultZone: http://localhost:8000/eureka/