#高可用服务化配置中心
server:
  port: 7001
spring:
  cloud:
    config:
      server:
        git:
            uri: https://自己的git存放地址
            search-paths: config-repo
            username: xxx
            password: xxx
  application:
    name: spring-cloud-config-server
eureka:
  client:
     service-url:
      defaultZone: http://localhost:8000/eureka/
